name: Publish SDK to PyPi

# Runs whenever a file is changed that matched the glob. Note: this
# means that the SDK is published separately from Orchest, this way
# user can build their own custom images for Orchest.
on:
  release:
    types: [published]

jobs:
  uploadsdk:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Upload SDK
        run: |
          cd orchest-sdk/python
          python setup.py sdist
          twine upload dist/* --non-interactive --skip-existing
